In [1]:
import tensorflow as tf
print(tf.__version__)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard


2.15.0


In [2]:
import pickle
import time

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

In [3]:
X = X/255.0 # normalized data

In [4]:
print(X.shape)

(277, 128, 128, 3)


In [5]:
# optimized architecture
dense_layers = [1]
layer_sizes = [64]
conv_layers = [3]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=1)

In [7]:
for dense_layer in dense_layers:
    for layer_size in layer_sizes:
        for conv_layer in conv_layers:
            NAME = "{}-conv-{}-nodes-{}-dense{}".format(conv_layer, layer_size, dense_layer, int(time.time()))
            tensorboard = TensorBoard(log_dir='logs/{}'.format(NAME))
            #print(NAME)
            
            model = Sequential()
            
            model.add(Conv2D(layer_size, (3, 3), input_shape=X.shape[1:]))
            model.add(Activation('relu'))
            model.add(MaxPooling2D(pool_size=(2, 2)))
            
            for l in range(conv_layer-1):
                model.add(Conv2D(layer_size, (3,3)))
                model.add(Activation('relu'))
                model.add(MaxPooling2D(pool_size=(2, 2)))
                
            model.add(Flatten())
            for l in range(dense_layer):
                model.add(Dense(128))
                model.add(Activation('relu'))
            
            model.add(Dense(5))
            model.add(Activation('softmax'))
            
            model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
            
            model.fit(X_train, y_train, epochs=30, validation_data=(X_val, y_val), callbacks=[tensorboard])




Epoch 1/10


8/8 [==============================] - 4s 328ms/step - loss: 24.8361 - accuracy: 0.2169 - val_loss: 7.8292 - val_accuracy: 0.2143
Epoch 2/10
8/8 [==============================] - 2s 297ms/step - loss: 4.1188 - accuracy: 0.2450 - val_loss: 2.5533 - val_accuracy: 0.2143
Epoch 3/10
8/8 [==============================] - 2s 277ms/step - loss: 2.0832 - accuracy: 0.1847 - val_loss: 1.6097 - val_accuracy: 0.2143
Epoch 4/10
8/8 [==============================] - 2s 283ms/step - loss: 1.6094 - accuracy: 0.2410 - val_loss: 1.6099 - val_accuracy: 0.1429
Epoch 5/10
8/8 [==============================] - 2s 285ms/step - loss: 1.6093 - accuracy: 0.2249 - val_loss: 1.6100 - val_accuracy: 0.1429
Epoch 6/10
8/8 [==============================] - 2s 271ms/step - loss: 1.6378 - accuracy: 0.2088 - val_loss: 1.6101 - val_accuracy: 0.1429
Epoch 7/10
8/8 [==============================] - 2s 262ms/step - loss: 1.6090 - accuracy: 0.2249 - val_loss: 1.6102 - val_accuracy: 0.1429
Epoch 8/10
8/8

8/8 [==============================] - 3s 338ms/step - loss: 3.0074 - accuracy: 0.2008 - val_loss: 1.6171 - val_accuracy: 0.1429
Epoch 2/10
8/8 [==============================] - 2s 301ms/step - loss: 1.5424 - accuracy: 0.2129 - val_loss: 1.5028 - val_accuracy: 0.3214
Epoch 3/10
8/8 [==============================] - 2s 290ms/step - loss: 1.3239 - accuracy: 0.5141 - val_loss: 1.1626 - val_accuracy: 0.6429
Epoch 4/10
8/8 [==============================] - 2s 304ms/step - loss: 0.9925 - accuracy: 0.5944 - val_loss: 0.8986 - val_accuracy: 0.6429
Epoch 5/10
8/8 [==============================] - 2s 312ms/step - loss: 0.6176 - accuracy: 0.8313 - val_loss: 0.7876 - val_accuracy: 0.5357
Epoch 6/10
8/8 [==============================] - 3s 320ms/step - loss: 0.4612 - accuracy: 0.8233 - val_loss: 0.8261 - val_accuracy: 0.5357
Epoch 7/10
8/8 [==============================] - 3s 328ms/step - loss: 0.4027 - accuracy: 0.8474 - val_loss: 0.6451 - val_accuracy: 0.7857
Epoch 8/10
8/8 [===============

8/8 [==============================] - 5s 681ms/step - loss: 0.2649 - accuracy: 0.9036 - val_loss: 0.7684 - val_accuracy: 0.7857
Epoch 10/10
8/8 [==============================] - 5s 678ms/step - loss: 0.2578 - accuracy: 0.8876 - val_loss: 1.2610 - val_accuracy: 0.6429
Epoch 1/10
8/8 [==============================] - 7s 694ms/step - loss: 1.6116 - accuracy: 0.2610 - val_loss: 1.5946 - val_accuracy: 0.2143
Epoch 2/10
8/8 [==============================] - 5s 676ms/step - loss: 1.5895 - accuracy: 0.2169 - val_loss: 1.5831 - val_accuracy: 0.1429
Epoch 3/10
8/8 [==============================] - 5s 654ms/step - loss: 1.5303 - accuracy: 0.2490 - val_loss: 1.5093 - val_accuracy: 0.1429
Epoch 4/10
8/8 [==============================] - 5s 654ms/step - loss: 1.3431 - accuracy: 0.3333 - val_loss: 1.1786 - val_accuracy: 0.3929
Epoch 5/10
8/8 [==============================] - 6s 705ms/step - loss: 0.9053 - accuracy: 0.5783 - val_loss: 0.8926 - val_accuracy: 0.6429
Epoch 6/10
8/8 [==============

8/8 [==============================] - 4s 482ms/step - loss: 0.3518 - accuracy: 0.9036 - val_loss: 0.8566 - val_accuracy: 0.6429
Epoch 8/10
8/8 [==============================] - 4s 493ms/step - loss: 0.2977 - accuracy: 0.9036 - val_loss: 0.6679 - val_accuracy: 0.7143
Epoch 9/10
8/8 [==============================] - 4s 484ms/step - loss: 0.2136 - accuracy: 0.9357 - val_loss: 0.6942 - val_accuracy: 0.6429
Epoch 10/10
8/8 [==============================] - 4s 494ms/step - loss: 0.2045 - accuracy: 0.9157 - val_loss: 0.7171 - val_accuracy: 0.7143
Epoch 1/10
8/8 [==============================] - 3s 307ms/step - loss: 2.7336 - accuracy: 0.1807 - val_loss: 1.5900 - val_accuracy: 0.2143
Epoch 2/10
8/8 [==============================] - 2s 295ms/step - loss: 1.5816 - accuracy: 0.2771 - val_loss: 1.5880 - val_accuracy: 0.3214
Epoch 3/10
8/8 [==============================] - 3s 314ms/step - loss: 1.4789 - accuracy: 0.2811 - val_loss: 1.3191 - val_accuracy: 0.5714
Epoch 4/10
8/8 [==============

Epoch 6/10
8/8 [==============================] - 6s 787ms/step - loss: 0.5638 - accuracy: 0.7912 - val_loss: 0.8612 - val_accuracy: 0.6429
Epoch 7/10
8/8 [==============================] - 6s 752ms/step - loss: 0.4753 - accuracy: 0.7831 - val_loss: 0.7855 - val_accuracy: 0.7500
Epoch 8/10
8/8 [==============================] - 6s 714ms/step - loss: 0.3543 - accuracy: 0.8514 - val_loss: 0.6604 - val_accuracy: 0.7500
Epoch 9/10
8/8 [==============================] - 6s 703ms/step - loss: 0.2869 - accuracy: 0.8876 - val_loss: 0.7188 - val_accuracy: 0.7500
Epoch 10/10
8/8 [==============================] - 5s 679ms/step - loss: 0.2430 - accuracy: 0.8916 - val_loss: 0.8529 - val_accuracy: 0.6786
Epoch 1/10
8/8 [==============================] - 7s 721ms/step - loss: 1.6280 - accuracy: 0.2369 - val_loss: 1.5997 - val_accuracy: 0.2143
Epoch 2/10
8/8 [==============================] - 6s 697ms/step - loss: 1.5962 - accuracy: 0.2289 - val_loss: 1.5937 - val_accuracy: 0.1786
Epoch 3/10
8/8 [===

8/8 [==============================] - 4s 474ms/step - loss: 1.4837 - accuracy: 0.3735 - val_loss: 1.5392 - val_accuracy: 0.2143
Epoch 5/10
8/8 [==============================] - 4s 473ms/step - loss: 1.2869 - accuracy: 0.4337 - val_loss: 1.2093 - val_accuracy: 0.3929
Epoch 6/10
8/8 [==============================] - 4s 480ms/step - loss: 0.9916 - accuracy: 0.6265 - val_loss: 0.9754 - val_accuracy: 0.6071
Epoch 7/10
8/8 [==============================] - 4s 487ms/step - loss: 0.7593 - accuracy: 0.7028 - val_loss: 0.8373 - val_accuracy: 0.6786
Epoch 8/10
8/8 [==============================] - 4s 499ms/step - loss: 0.4958 - accuracy: 0.8554 - val_loss: 0.9349 - val_accuracy: 0.5714
Epoch 9/10
8/8 [==============================] - 4s 491ms/step - loss: 0.4097 - accuracy: 0.8233 - val_loss: 0.7468 - val_accuracy: 0.7143
Epoch 10/10
8/8 [==============================] - 4s 484ms/step - loss: 0.3562 - accuracy: 0.8554 - val_loss: 0.7021 - val_accuracy: 0.6786
Epoch 1/10
8/8 [==============

8/8 [==============================] - 6s 698ms/step - loss: 1.5705 - accuracy: 0.2570 - val_loss: 1.5521 - val_accuracy: 0.2143
Epoch 3/10
8/8 [==============================] - 5s 663ms/step - loss: 1.4303 - accuracy: 0.3253 - val_loss: 1.3157 - val_accuracy: 0.2857
Epoch 4/10
8/8 [==============================] - 6s 701ms/step - loss: 0.9156 - accuracy: 0.5984 - val_loss: 0.9052 - val_accuracy: 0.7500
Epoch 5/10
8/8 [==============================] - 5s 671ms/step - loss: 0.6537 - accuracy: 0.6988 - val_loss: 0.9662 - val_accuracy: 0.6071
Epoch 6/10
8/8 [==============================] - 6s 747ms/step - loss: 0.6183 - accuracy: 0.7269 - val_loss: 0.8822 - val_accuracy: 0.7500
Epoch 7/10
8/8 [==============================] - 6s 721ms/step - loss: 0.4325 - accuracy: 0.8072 - val_loss: 0.6606 - val_accuracy: 0.7857
Epoch 8/10
8/8 [==============================] - 5s 680ms/step - loss: 0.2737 - accuracy: 0.8956 - val_loss: 0.8745 - val_accuracy: 0.8214
Epoch 9/10
8/8 [===============

In [8]:
model.save('CNN_leafs.model')

INFO:tensorflow:Assets written to: CNN_leafs.model\assets


INFO:tensorflow:Assets written to: CNN_leafs.model\assets


In [9]:
model = tf.keras.models.load_model('CNN_leafs.model', compile=False)
predictions = model.predict(X_val)

1/1 [==============================] - 0s 305ms/step


In [10]:
import numpy as np
pred_classes = []
for pred in predictions:
    pred_classes.append(np.argmax(pred))
pred_classes = np.array(pred_classes)
print("PREDICTIONS: ")
print(pred_classes)
print("TRUE VALUES: ")
print(y_val)

PREDICTIONS: 
[2 3 1 0 0 0 2 3 1 2 2 0 3 4 0 2 1 2 3 1 3 2 4 0 4 3 3 2]
TRUE VALUES: 
[1 3 0 0 0 0 2 4 1 2 2 1 3 4 0 2 1 2 3 1 4 1 4 0 4 3 4 2]


In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_val, pred_classes))

[[5 1 0 0 0]
 [1 3 2 0 0]
 [0 0 6 0 0]
 [0 0 0 4 0]
 [0 0 0 3 3]]


In [12]:
wrong_predictions = 0
for i in range(len(y_val)):
    if y_val[i] != pred_classes[i]:
        print(f"TRUE: {y_val[i]} PRED: {pred_classes[i]}")
        wrong_predictions += 1

TRUE: 1 PRED: 2
TRUE: 0 PRED: 1
TRUE: 4 PRED: 3
TRUE: 1 PRED: 0
TRUE: 4 PRED: 3
TRUE: 1 PRED: 2
TRUE: 4 PRED: 3


In [13]:
# 3 out of 7 are mistakes between oak and maple

In [14]:
accuracy = 1 - (wrong_predictions/len(y_val))
print(accuracy)

0.75
