In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os

!pip install opencv-python
import cv2
data_dir = "C:\\Users\\adria\\Documents\\GitHub\\leaf-count-cv\\"
categories = ["aspen", "birch", "hazel", "maple", "oak"]

Defaulting to user installation because normal site-packages is not writeable


In [2]:
img_size = 50
training_data = []
def create_training_data():
    for category in categories:
        path = os.path.join(data_dir, category)
        class_num = categories.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img), cv2.IMREAD_GRAYSCALE)
                new_array = cv2.resize(img_array, (img_size, img_size))
                training_data.append([new_array, class_num])
            except Exception as e:
                 print("general exception", e, os.path.join(path,img))

                    
create_training_data()

In [3]:
print(len(training_data))

162


In [4]:
import random

random.shuffle(training_data)

In [5]:
for sample in training_data[:10]:
    print(sample[1])

2
4
2
0
1
2
1
3
4
0


In [6]:
X = []
y = []

for features,label in training_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, img_size, img_size, 1))

X = np.array(X).reshape(-1, img_size, img_size, 1)
y = np.array(y)

[[[[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]

  [[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]

  [[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]

  ...

  [[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]

  [[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]

  [[254]
   [254]
   [254]
   ...
   [254]
   [254]
   [254]]]]


In [7]:
print(X.shape)

(162, 50, 50, 1)


In [8]:
import pickle

In [9]:
pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()